baseURL = 'http://example.org/'
languageCode = 'de'
title = 'Laaer Tennisclub'
theme = "hugo-universal-theme"
defaultContentLanguage = "de"
style = "red"

[params]
	disabled_logo = true
	about_us = "<p>Das sind wir ...</p>"
	contact_url = "/contact"
	address = """
		<p class="text-uppercase"><strong>Laaer Tennisclub</strong>
		<br>Eichamtstraße
		</p>
		"""

[params.footer.recent_posts]
	enable = true

[params.carouselHomepage]
	enable = true
	auto_play = true

[params.see_more]
	enable = true
	icon = "far fa-file-alt"
	title = "Do you want to see more?"

[[menu.main]]
	name = "Home"
	identifier = "menu.home"
	url = "/"
	weight = 1

[[menu.main]]
	name = "Über uns"
	identifier = "menu.about"
	url = "/about"
	weight = 2

[[menu.main]]
	name = "News"
	identifier = "menu.news"
	url = "/news"
	weight = 3
